[workspace]
members = ["crates/irohole-proto", "crates/irohole-core", "crates/irohole-cli", "plugins/irohole-plugin-tcp", "plugins/irohole-plugins"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { version = "4", default-features = false, features = ["derive", "std", "help", "usage", "error-context"] }
postcard = { version = "1", default-features = false, features = ["alloc"] }
iroh = { version = "1.3", default-features = false, features = ["tls-ring"] }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
tokio = { version = "1", default-features = false, features = ["rt", "rt-multi-thread", "macros", "io-util", "io-std", "net", "time", "sync", "signal"] }
tracing = { version = "0.1", default-features = false, features = ["std", "attributes"] }

irohole-proto = { path = "crates/irohole-proto" }
irohole-core = { path = "crates/irohole-core" }
irohole-plugin-tcp = { path = "plugins/irohole-plugin-tcp" }
irohole-plugins = { path = "plugins/irohole-plugins" }

[workspace.lints.rust]
unused = "warn"
